name: brana
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 

  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_hooks: ^0.2.4
  
  shared_preferences: ^2.0.6
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  floor: ^1.5.0
  sqflite: ^2.3.3+1
  morphy_annotation: ^1.2.0
  dart_mappable: ^4.2.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  collection: ^1.18.0 
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.0
  logger: ^1.0.0
  animations: ^2.0.11
  stacked_themes: ^0.3.12
  shimmer_animation: ^2.2.1
  easy_localization: ^3.0.7

  
dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  floor_generator: ^1.5.0
  morphy: ^1.2.0
  dart_mappable_builder: ^4.2.3
  fake_async: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/start_up/
    - assets/intro/
    - assets/home/
    - assets/translations/

