import 'package:flutter/material.dart';

final BRANA_APP_LIGHT_THEME = ThemeData(
  typography: Typography(),
  textTheme: const TextTheme(
    displayLarge: TextStyle(
      inherit: false,
      fontSize: 32,
      color: Colors.black,
      fontWeight: FontWeight.w700,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayMedium: TextStyle(
      inherit: false,
      fontSize: 24,
      color: Colors.black,
      fontWeight: FontWeight.w700,
      textBaseline: TextBaseline.alphabetic,
    ),
    displaySmall: TextStyle(
      inherit: false,
      fontSize: 18,
      color: Colors.black,
      fontWeight: FontWeight.w700,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineLarge: TextStyle(
      inherit: false,
      fontSize: 24,
      color: Colors.black,
      fontWeight: FontWeight.w600,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineMedium: TextStyle(
      inherit: false,
      fontSize: 20,
      color: Colors.black,
      fontWeight: FontWeight.w600,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineSmall: TextStyle(
      inherit: false,
      fontSize: 16,
      color: Colors.black,
      fontWeight: FontWeight.w600,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleLarge: TextStyle(
      inherit: false,
      fontSize: 24,
      color: Colors.black,
      fontWeight: FontWeight.w500,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleMedium: TextStyle(
      inherit: false,
      fontSize: 20,
      color: Colors.black,
      fontWeight: FontWeight.w500,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleSmall: TextStyle(
      fontSize: 16,
      inherit: false,
      color: Colors.black,
      fontWeight: FontWeight.w500,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodyLarge: TextStyle(
      fontSize: 18,
      inherit: false,
      color: Colors.black,
      fontWeight: FontWeight.w400,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodyMedium: TextStyle(
      inherit: false,
      fontSize: 16,
      color: Colors.black,
      fontWeight: FontWeight.w400,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodySmall: TextStyle(
      fontSize: 14,
      inherit: false,
      color: Colors.black,
      fontWeight: FontWeight.w400,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelLarge: TextStyle(
      fontSize: 16,
      inherit: false,
      color: Colors.black,
      fontWeight: FontWeight.w300,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelMedium: TextStyle(
      fontSize: 14,
      inherit: false,
      color: Colors.black,
      fontWeight: FontWeight.w300,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelSmall: TextStyle(
      fontSize: 12,
      inherit: false,
      color: Colors.black,
      fontWeight: FontWeight.w300,
      textBaseline: TextBaseline.alphabetic,
    ),
  ),
  listTileTheme: const ListTileThemeData(
    titleTextStyle: TextStyle(
      color: Colors.black,
      inherit: false,
      fontSize: 16,
      fontWeight: FontWeight.w600,
      textBaseline: TextBaseline.alphabetic,
    ),
    subtitleTextStyle: TextStyle(
      inherit: false,
      color: Colors.black,
      fontSize: 14,
      textBaseline: TextBaseline.alphabetic,
    ),
  ),
  scaffoldBackgroundColor: const Color(0xffF6F7F9),
  primaryColor: const Color(0xff24A19C),
  primaryColorLight: Colors.grey[700],
  canvasColor: Colors.transparent,
  cardColor: Colors.white,
  shadowColor: Colors.grey,
  appBarTheme: AppBarTheme(
    backgroundColor: Colors.white,
    elevation: 0,
    iconTheme: IconThemeData(color: Colors.grey[700]),
    titleTextStyle: const TextStyle(
      fontSize: 20,
      inherit: false,
      color: Colors.black,
      fontWeight: FontWeight.w500,
      textBaseline: TextBaseline.alphabetic,
    ),
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: Colors.white,
    selectedItemColor: Color(0xff24A19C),
    unselectedItemColor: Colors.grey,
  ),
);

final BRANA_APP_DARK_THEME = ThemeData(
  typography: Typography(),
  textTheme: const TextTheme(
    displayLarge: TextStyle(
      fontSize: 32,
      inherit: false,
      color: Colors.white,
      fontWeight: FontWeight.w700,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayMedium: TextStyle(
      fontSize: 24,
      inherit: false,
      color: Colors.white,
      fontWeight: FontWeight.w700,
      textBaseline: TextBaseline.alphabetic,
    ),
    displaySmall: TextStyle(
      fontSize: 18,
      inherit: false,
      color: Colors.white,
      fontWeight: FontWeight.w700,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineLarge: TextStyle(
      fontSize: 24,
      inherit: false,
      color: Colors.white,
      fontWeight: FontWeight.w600,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineMedium: TextStyle(
      fontSize: 20,
      color: Colors.white,
      inherit: false,
      fontWeight: FontWeight.w600,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineSmall: TextStyle(
      fontSize: 16,
      color: Colors.white,
      inherit: false,
      fontWeight: FontWeight.w600,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleLarge: TextStyle(
      fontSize: 24,
      color: Colors.white,
      inherit: false,
      fontWeight: FontWeight.w500,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleMedium: TextStyle(
      fontSize: 20,
      color: Colors.white,
      inherit: false,
      textBaseline: TextBaseline.alphabetic,
      fontWeight: FontWeight.w500,
    ),
    titleSmall: TextStyle(
      fontSize: 16,
      inherit: false,
      textBaseline: TextBaseline.alphabetic,
      color: Colors.white,
      fontWeight: FontWeight.w500,
    ),
    bodyLarge: TextStyle(
      fontSize: 18,
      inherit: false,
      color: Colors.white,
      textBaseline: TextBaseline.alphabetic,
      fontWeight: FontWeight.w400,
    ),
    bodyMedium: TextStyle(
      fontSize: 16,
      inherit: false,
      color: Colors.white,
      textBaseline: TextBaseline.alphabetic,
      fontWeight: FontWeight.w400,
    ),
    bodySmall: TextStyle(
      fontSize: 14,
      inherit: false,
      color: Colors.white,
      fontWeight: FontWeight.w400,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelLarge: TextStyle(
      fontSize: 16,
      inherit: false,
      color: Colors.white,
      fontWeight: FontWeight.w300,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelMedium: TextStyle(
      fontSize: 14,
      inherit: false,
      color: Colors.white,
      textBaseline: TextBaseline.alphabetic,
      fontWeight: FontWeight.w300,
    ),
    labelSmall: TextStyle(
      fontSize: 12,
      inherit: false,
      color: Colors.white,
      textBaseline: TextBaseline.alphabetic,
      fontWeight: FontWeight.w300,
    ),
  ),
  scaffoldBackgroundColor: const Color.fromARGB(255, 41, 41, 41),
  primaryColor: const Color(0xff064F4C),
  primaryColorLight: Colors.white,
  canvasColor: const Color.fromARGB(255, 41, 41, 41),
  cardColor: Colors.black,
  appBarTheme: AppBarTheme(
    backgroundColor: Colors.black,
    elevation: 0,
    iconTheme: IconThemeData(color: Colors.grey[700]),
    titleTextStyle: const TextStyle(
      fontSize: 20,
      inherit: false,
      color: Colors.white,
      textBaseline: TextBaseline.alphabetic,
      fontWeight: FontWeight.w500,
    ),
  ),
  listTileTheme: const ListTileThemeData(
    titleTextStyle: TextStyle(
      textBaseline: TextBaseline.alphabetic,
      color: Colors.white,
      inherit: false,
      fontSize: 16,
      fontWeight: FontWeight.w600,
    ),
    subtitleTextStyle: TextStyle(
      inherit: false,
      color: Colors.white,
      fontSize: 14,
      textBaseline: TextBaseline.alphabetic,
    ),
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: Colors.black,
    selectedItemColor: Colors.white,
    unselectedItemColor: Colors.grey,
  ),
);
